using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace ContainerAndLootPatcher;

public class Program
{
    private static Lazy<Settings> _settings = null!;
    private static Settings Settings => _settings.Value;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .Run(args);
    }

    private static IPatcherState<ISkyrimMod, ISkyrimModGetter>? _state;
    internal static IPatcherState<ISkyrimMod, ISkyrimModGetter> State => _state!;

    private static void LogSectionHeader(string title)
    {
        Console.WriteLine();
        Console.WriteLine("============================================================");
        Console.WriteLine($"  {title}");
        Console.WriteLine("============================================================");
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        _state = state;

        var anyPurgeEnabled = Settings.RemoveGoldFromContainers || Settings.RemoveLockpicksFromContainers;
        var needAnchorSets = anyPurgeEnabled || Settings.BypassScarcityOnBossLoot;

        // Build anchor-equivalent sets up front so they can be shared between
        // boss-bypass clone filtering and the purges themselves.
        HashSet<FormKey> goldAnchorEquivalents = [];
        HashSet<FormKey> lockpickAnchorEquivalents = [];
        HashSet<FormKey> allAnchorEquivalents = [];
        if (needAnchorSets)
        {
            goldAnchorEquivalents = BuildAnchorEquivalentSet(state, GoldPurgeRule);
            lockpickAnchorEquivalents = BuildAnchorEquivalentSet(state, LockpickPurgeRule);
            allAnchorEquivalents = new HashSet<FormKey>(goldAnchorEquivalents);
            allAnchorEquivalents.UnionWith(lockpickAnchorEquivalents);
        }

        if (Settings.BypassScarcityOnBossLoot)
        {
            // Filter from clone entries any anchor-equivalents from ENABLED purge rules,
            // so cloned Leveled Lists don't reintroduce items the user wants stripped.
            // Preserve verbatim any LVLI on a rule's exclusion list (e.g. LootPerkGoldenTouch)
            // since its entire purpose is to drop the otherwise-purged item.
            var cloneEntryFilter = new HashSet<FormKey>();
            var cloneEntryPreserve = new HashSet<FormKey>();
            if (Settings.RemoveGoldFromContainers)
            {
                cloneEntryFilter.UnionWith(goldAnchorEquivalents);
                cloneEntryPreserve.UnionWith(GoldPurgeRule.Exclusions);
            }
            if (Settings.RemoveLockpicksFromContainers)
            {
                cloneEntryFilter.UnionWith(lockpickAnchorEquivalents);
                cloneEntryPreserve.UnionWith(LockpickPurgeRule.Exclusions);
            }
            BypassScarcityOnBossLoot(state, cloneEntryFilter, cloneEntryPreserve);
        }

        if (anyPurgeEnabled)
        {
            var merchantContainerBases = BuildMerchantContainerBaseSet(state);
            var singlePurposeContainers = BuildSinglePurposeContainerSet(state, allAnchorEquivalents);

            var containerSkipSet = new HashSet<FormKey>(merchantContainerBases);
            containerSkipSet.UnionWith(singlePurposeContainers);

            if (Settings.RemoveGoldFromContainers)
                PurgeAnchorEquivalentsFromContainers(state, GoldPurgeRule, goldAnchorEquivalents, containerSkipSet);

            if (Settings.RemoveLockpicksFromContainers)
                PurgeAnchorEquivalentsFromContainers(state, LockpickPurgeRule, lockpickAnchorEquivalents, containerSkipSet);
        }

        if (Settings.LockRelatedLootCompatibility)
            ApplyLockRelatedLootCompatibility(state);
    }

    private static readonly string[] KnownScarcityPluginNames =
    {
        "Scarcity SE - Less Loot Mod.esp",
        "Scarcity - Less Loot Mod.esp"
    };
    private static HashSet<FormKey> _scarcityAffectedLists = [];
    private static Dictionary<FormKey, FormKey> _scarcityFreeCloneMap = new();

    private static void BypassScarcityOnBossLoot(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, HashSet<FormKey> cloneEntryFilter, HashSet<FormKey> cloneEntryPreserve)
    {
        LogSectionHeader("Bypass Scarcity on Boss Loot");

        var scarcityKey = state.LoadOrder.Keys.FirstOrDefault(k =>
            KnownScarcityPluginNames.Any(name => k.FileName.String.Equals(name, StringComparison.OrdinalIgnoreCase)));
        if (scarcityKey.IsNull)
        {
            Console.WriteLine($"Warning: Scarcity plugin not found in the load order (checked: {string.Join(", ", KnownScarcityPluginNames)}). Boss-bypass step will be skipped.");
            return;
        }

        Console.WriteLine("Bypassing Scarcity on 'Boss' Container and NPC loot...");

        _scarcityAffectedLists = [];
        _scarcityFreeCloneMap = new Dictionary<FormKey, FormKey>();

        foreach (var lvli in state.LoadOrder.PriorityOrder.LeveledItem().WinningOverrides())
        {
            var globalKey = lvli.Global.FormKeyNullable;
            if (globalKey is null)
                continue;
            if (globalKey.Value.ModKey == scarcityKey)
                _scarcityAffectedLists.Add(lvli.FormKey);
        }

        if (_scarcityAffectedLists.Count == 0)
        {
            Console.WriteLine("  No Leveled Lists currently use a Scarcity Global - nothing to bypass.");
            return;
        }
        Console.WriteLine($"  Identified {_scarcityAffectedLists.Count} Scarcity-gated Leveled List(s).");
        if (cloneEntryFilter.Count > 0)
            Console.WriteLine($"  Cloned Leveled Lists will drop {cloneEntryFilter.Count} purge-set entry/entries; {cloneEntryPreserve.Count} excluded LVLI(s) will be cloned verbatim.");

        var containersPatched = 0;
        var npcsPatched = 0;

        foreach (var containerCtx in state.LoadOrder.PriorityOrder.Container().WinningContextOverrides())
        {
            var container = containerCtx.Record;
            if (container.EditorID is null || !container.EditorID.Contains("Boss", StringComparison.OrdinalIgnoreCase))
                continue;
            if (container.Items is null || container.Items.Count == 0)
                continue;
            if (!container.Items.Any(e => _scarcityAffectedLists.Contains(e.Item.Item.FormKey)))
                continue;

            var patch = containerCtx.GetOrAddAsOverride(state.PatchMod);
            var rewired = RewireScarcityRefsInItemList(state, patch.Items, cloneEntryFilter, cloneEntryPreserve);
            if (rewired == 0)
                continue;

            containersPatched++;
            Console.WriteLine($"  Container {container.EditorID}: rewired {rewired} Scarcity-gated entry/entries");
        }

        foreach (var npcCtx in state.LoadOrder.PriorityOrder.Npc().WinningContextOverrides())
        {
            var npc = npcCtx.Record;
            if (npc.EditorID is null || !npc.EditorID.Contains("Boss", StringComparison.OrdinalIgnoreCase))
                continue;
            if (npc.Items is null || npc.Items.Count == 0)
                continue;
            if (!npc.Items.Any(e => _scarcityAffectedLists.Contains(e.Item.Item.FormKey)))
                continue;

            var patch = npcCtx.GetOrAddAsOverride(state.PatchMod);
            var rewired = RewireScarcityRefsInItemList(state, patch.Items, cloneEntryFilter, cloneEntryPreserve);
            if (rewired == 0)
                continue;

            npcsPatched++;
            Console.WriteLine($"  NPC {npc.EditorID}: rewired {rewired} Scarcity-gated entry/entries");
        }

        Console.WriteLine($"Patched {containersPatched} container(s) and {npcsPatched} NPC(s) using {_scarcityFreeCloneMap.Count} Scarcity-free Leveled List clone(s).");
    }

    private static int RewireScarcityRefsInItemList(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, IList<ContainerEntry>? items, HashSet<FormKey> cloneEntryFilter, HashSet<FormKey> cloneEntryPreserve)
    {
        if (items is null || items.Count == 0)
            return 0;

        var count = 0;
        foreach (var entry in items)
        {
            var refKey = entry.Item.Item.FormKey;
            if (!_scarcityAffectedLists.Contains(refKey))
                continue;

            // If this Scarcity-gated ref is itself in the purge filter (e.g. a pure-gold LVLI),
            // skip the rewire and let the gold/lockpick purge remove it cleanly. Otherwise we'd
            // create an empty clone and leave a useless reference behind on the container.
            if (cloneEntryFilter.Contains(refKey))
                continue;

            var cloneKey = GetOrCreateScarcityFreeClone(state, refKey, cloneEntryFilter, cloneEntryPreserve);
            entry.Item.Item.SetTo(cloneKey);
            count++;
        }
        return count;
    }

    private static FormKey GetOrCreateScarcityFreeClone(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, FormKey originalKey, HashSet<FormKey> cloneEntryFilter, HashSet<FormKey> cloneEntryPreserve)
    {
        if (_scarcityFreeCloneMap.TryGetValue(originalKey, out var existing))
            return existing;

        if (!state.LinkCache.TryResolve<ILeveledItemGetter>(originalKey, out var original))
            return originalKey;

        var clone = new LeveledItem(state.PatchMod.GetNextFormKey(), state.PatchMod.SkyrimRelease)
        {
            EditorID = BuildCloneEditorId(original.EditorID, originalKey)
        };
        state.PatchMod.LeveledItems.Add(clone);
        _scarcityFreeCloneMap[originalKey] = clone.FormKey;

        clone.ChanceNone = original.ChanceNone;
        clone.Flags = original.Flags;
        // Global is deliberately left null - that's the whole point of the clone.

        // LVLIs on a purge rule's exclusion list (e.g. LootPerkGoldenTouch) are cloned verbatim:
        // their job is precisely to drop the otherwise-purged item, so we must keep their entries intact.
        var preserveVerbatim = cloneEntryPreserve.Contains(originalKey);

        if (original.Entries is null || original.Entries.Count <= 0)
            return clone.FormKey;

        clone.Entries = [];
        foreach (var entryGetter in original.Entries)
        {
            var newEntry = entryGetter.DeepCopy();

            if (preserveVerbatim)
            {
                // Excluded LVLI: copy entries verbatim, no filtering, no recursion.
                clone.Entries.Add(newEntry);
                continue;
            }

            if (newEntry.Data is null)
            {
                clone.Entries.Add(newEntry);
                continue;
            }

            var entryRefKey = newEntry.Data.Reference.FormKey;

            // Drop entries that are in any active purge set (gold, lockpicks, etc.) -
            // this is the fix for clones carrying gold/lockpicks through to boss containers.
            if (cloneEntryFilter.Contains(entryRefKey))
                continue;

            // Recurse into Scarcity-gated sub-lists to keep the whole subtree Scarcity-free.
            if (_scarcityAffectedLists.Contains(entryRefKey))
            {
                var subCloneKey = GetOrCreateScarcityFreeClone(state, entryRefKey, cloneEntryFilter, cloneEntryPreserve);
                newEntry.Data.Reference.SetTo(subCloneKey);
            }

            clone.Entries.Add(newEntry);
        }

        return clone.FormKey;
    }

    private static string BuildCloneEditorId(string? originalEditorId, FormKey originalKey)
    {
        const string suffix = "_CLP";
        const int maxLength = 99;
        
        var baseId = string.IsNullOrEmpty(originalEditorId)
            ? $"LVLI_{originalKey.IDString()}"
            : originalEditorId;
        
        if (baseId.Length + suffix.Length > maxLength)
            baseId = baseId[..(maxLength - suffix.Length)];
        
        return baseId + suffix;
    }

    private sealed record AnchorPurgeRule(
        string FeatureName,
        FormKey Anchor,
        HashSet<FormKey> Exclusions);

    private static readonly AnchorPurgeRule GoldPurgeRule = new(
        FeatureName: "gold",
        Anchor: FormKey.Factory("00000F:Skyrim.esm"), // Gold001 MiscItem
        Exclusions:
        [
            FormKey.Factory("10FD8B:Skyrim.esm"), // LootPerkGoldenTouch - Transmute perk gold drop
            FormKey.Factory("10C1CC:Skyrim.esm") // PerkMasterTraderGold - Master Trader speech perk extra gold
        ]);

    private static readonly AnchorPurgeRule LockpickPurgeRule = new(
        FeatureName: "lockpicks",
        Anchor: FormKey.Factory("00000A:Skyrim.esm"), // Lockpick MiscItem
        Exclusions: []);

    private static void PurgeAnchorEquivalentsFromContainers(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, AnchorPurgeRule rule, HashSet<FormKey> purgeSet, HashSet<FormKey> containerSkipSet)
    {
        LogSectionHeader($"Remove {rule.FeatureName} from Containers");

        if (purgeSet.Count == 0)
        {
            Console.WriteLine($"  Could not locate the {rule.FeatureName} anchor ({rule.Anchor}) in the load order - skipping {rule.FeatureName} removal.");
            return;
        }

        Console.WriteLine($"  Identified {purgeSet.Count} {rule.FeatureName}-equivalent FormKey(s) (anchor plus Leveled Lists that resolve to only {rule.FeatureName}).");
        var containerCount = 0;
        var entryCount = 0;
        var containersSkipped = 0;

        foreach (var containerContext in state.LoadOrder.PriorityOrder.Container().WinningContextOverrides())
        {
            var container = containerContext.Record;
            if (container.Items is null || container.Items.Count == 0)
                continue;

            var matchCount = container.Items.Count(e => purgeSet.Contains(e.Item.Item.FormKey));
            if (matchCount == 0)
                continue;

            if (containerSkipSet.Contains(container.FormKey))
            {
                containersSkipped++;
                continue;
            }

            var patch = containerContext.GetOrAddAsOverride(state.PatchMod);
            var removed = patch.Items?.RemoveAll(e => purgeSet.Contains(e.Item.Item.FormKey)) ?? 0;

            if (removed == 0)
                continue;

            containerCount++;
            entryCount += removed;
            Console.WriteLine($"  Removed {removed} {rule.FeatureName} entry/entries from {container.EditorID ?? container.FormKey.ToString()}");
        }

        Console.WriteLine($"Modified {containerCount} Container(s), removed {entryCount} {rule.FeatureName} entry/entries total. Skipped {containersSkipped} excluded Container(s) (merchant chests + single-purpose).");
    }

    private static HashSet<FormKey> BuildSinglePurposeContainerSet(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, HashSet<FormKey> anchorEquivalents)
    {
        LogSectionHeader("Build Single-Purpose Container Exclusion Set");

        var set = new HashSet<FormKey>();
        var examined = 0;

        if (anchorEquivalents.Count == 0)
        {
            Console.WriteLine("  No anchor-equivalent FormKeys provided; no single-purpose containers can be identified.");
            return set;
        }

        foreach (var container in state.LoadOrder.PriorityOrder.Container().WinningOverrides())
        {
            if (container.Items is null || container.Items.Count == 0)
                continue;
            
            examined++;

            var allMatch = container.Items.All(entry => anchorEquivalents.Contains(entry.Item.Item.FormKey));
            if (allMatch)
                set.Add(container.FormKey);
        }

        Console.WriteLine($"  Examined {examined} Container(s) with items; identified {set.Count} as single-purpose (item list contains only anchor-equivalents).");
        return set;
    }

    private static HashSet<FormKey> BuildMerchantContainerBaseSet(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        LogSectionHeader("Build Merchant Chest Exclusion Set");
        
        var set = new HashSet<FormKey>();
        var factionsWithRef = 0;
        var unresolvedRefs = 0;

        foreach (var faction in state.LoadOrder.PriorityOrder.Faction().WinningOverrides())
        {
            var merchantRefKey = faction.MerchantContainer.FormKey;
            if (merchantRefKey.IsNull)
                continue;

            factionsWithRef++;

            if (!state.LinkCache.TryResolve<IPlacedObjectGetter>(merchantRefKey, out var refr))
            {
                unresolvedRefs++;
                continue;
            }

            var baseKey = refr.Base.FormKey;
            if (baseKey.IsNull)
                continue;

            set.Add(baseKey);
        }

        Console.WriteLine($"  Found {factionsWithRef} Faction(s) with a Merchant Container reference; resolved to {set.Count} distinct base Container record(s)" +
                          (unresolvedRefs > 0 ? $" ({unresolvedRefs} REFR(s) could not be resolved)" : "") + ".");
        return set;
    }

    private static HashSet<FormKey> BuildAnchorEquivalentSet(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, AnchorPurgeRule rule)
    {
        var set = new HashSet<FormKey>();

        if (!state.LinkCache.TryResolve<Mutagen.Bethesda.Plugins.Records.IMajorRecordGetter>(rule.Anchor, out _))
            return set;

        set.Add(rule.Anchor);

        var leveledItems = state.LoadOrder.PriorityOrder.LeveledItem().WinningOverrides().ToList();

        bool changed;
        do
        {
            changed = false;
            foreach (var lvli in leveledItems)
            {
                if (set.Contains(lvli.FormKey))
                    continue;

                if (rule.Exclusions.Contains(lvli.FormKey))
                    continue;

                if (lvli.Entries is null || lvli.Entries.Count == 0)
                    continue;

                var allMatch = true;
                foreach (var entry in lvli.Entries)
                {
                    var refKey = entry.Data?.Reference.FormKey;
                    if (refKey is null || !set.Contains(refKey.Value))
                    {
                        allMatch = false;
                        break;
                    }
                }

                if (allMatch)
                {
                    set.Add(lvli.FormKey);
                    changed = true;
                }
            }
        } while (changed);

        return set;
    }

    private const string LockRelatedLootPluginName = "LockRelatedLoot.esp";
    private static void ApplyLockRelatedLootCompatibility(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        LogSectionHeader("LockRelatedLoot Compatibility");

        var lrlKey = state.LoadOrder.Keys.FirstOrDefault(k => k.FileName.String.Equals(LockRelatedLootPluginName, StringComparison.OrdinalIgnoreCase));

        if (lrlKey.IsNull)
        {
            Console.WriteLine($"{LockRelatedLootPluginName} not present in load order - skipping LRL compatibility step.");
            return;
        }

        Console.WriteLine($"Applying {LockRelatedLootPluginName} compatibility...");

        var lrlMod = state.LoadOrder[lrlKey].Mod;
        if (lrlMod is null)
        {
            Console.WriteLine($"  Could not read {LockRelatedLootPluginName} - skipping.");
            return;
        }

        var updatedCount = 0;
        var scriptsApplied = 0;

        foreach (var lrlContainer in lrlMod.Containers)
        {
            var lrlScripts = lrlContainer.VirtualMachineAdapter?.Scripts;
            if (lrlScripts is null || lrlScripts.Count == 0)
                continue;

            if (!state.LinkCache.TryResolveContext<IContainer, IContainerGetter>(lrlContainer.FormKey, out var winningCtx))
                continue;

            if (winningCtx.ModKey == lrlKey)
                continue;

            var winningRecord = winningCtx.Record;
            var existingScriptNames = new HashSet<string>(
                winningRecord.VirtualMachineAdapter?.Scripts.Select(s => s.Name) ?? Enumerable.Empty<string>(),
                StringComparer.OrdinalIgnoreCase);

            var scriptsToAdd = lrlScripts
                .Where(s => !existingScriptNames.Contains(s.Name))
                .ToList();

            if (scriptsToAdd.Count == 0)
                continue;

            var patch = winningCtx.GetOrAddAsOverride(state.PatchMod);
            patch.VirtualMachineAdapter ??= new VirtualMachineAdapter();
            foreach (var script in scriptsToAdd)
                patch.VirtualMachineAdapter.Scripts.Add(script.DeepCopy());

            updatedCount++;
            scriptsApplied += scriptsToAdd.Count;
            Console.WriteLine($"  Added {scriptsToAdd.Count} script(s) to {winningRecord.EditorID ?? winningRecord.FormKey.ToString()}");
        }

        Console.WriteLine($"Updated {updatedCount} container(s) with {scriptsApplied} script entry/entries from {LockRelatedLootPluginName}.");
    }
}
