using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace ContainerAndLootPatcher;

public class Program
{
    private static Lazy<Settings> _settings = null!;
    private static Settings Settings => _settings.Value;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .Run(args);
    }

    private static IPatcherState<ISkyrimMod, ISkyrimModGetter>? _state;
    internal static IPatcherState<ISkyrimMod, ISkyrimModGetter> State => _state!;

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        _state = state;

        if (Settings.RevertBossChestChanges)
            RevertBossLeveledItems(state);

        if (Settings.RemoveGoldFromContainers)
            RemoveGoldFromContainers(state);

        if (Settings.LockRelatedLootCompatibility)
            ApplyLockRelatedLootCompatibility(state);
    }

    private static readonly string[] KnownScarcityPluginNames =
    {
        "Scarcity SE - Less Loot Mod.esp",
        "Scarcity - Less Loot Mod.esp"
    };
    
    private static void RevertBossLeveledItems(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        
        var scarcityKey = state.LoadOrder.Keys.FirstOrDefault(k => KnownScarcityPluginNames.Any(name => k.FileName.String.Equals(name, StringComparison.OrdinalIgnoreCase)));
        if (scarcityKey.IsNull)
        {
            Console.WriteLine($"Warning: Scarcity plugin not found in the load order (checked: {string.Join(", ", KnownScarcityPluginNames)}). Boss-revert step will be skipped.");
            return;
        }
        
        Console.WriteLine("Reverting Scarcity changes on 'Boss' Leveled Item records...");
        var revertedCount = 0;

        foreach (var leveledItemContext in state.LoadOrder.PriorityOrder.LeveledItem().WinningContextOverrides())
        {
            var leveledItem = leveledItemContext.Record;
            if (leveledItem.EditorID is null || !leveledItem.EditorID.Contains("Boss", StringComparison.OrdinalIgnoreCase))
                continue;

            var contexts = state.LinkCache
                .ResolveAllContexts<ILeveledItem, ILeveledItemGetter>(leveledItem.FormKey)
                .ToList();

            var scarcityIndex = contexts.FindIndex(c => c.ModKey == scarcityKey);
            if (scarcityIndex < 0)
                continue;

            if (scarcityIndex + 1 >= contexts.Count)
            {
                Console.WriteLine($"  Skipping {leveledItem.EditorID}: Scarcity is the sole record source, nothing to revert to.");
                continue;
            }

            var preScarcityContext = contexts[scarcityIndex + 1];
            var scarcityRecord = contexts[scarcityIndex].Record;
            var preScarcityRecord = preScarcityContext.Record;

            var winningGlobal = leveledItem.Global.FormKeyNullable;
            var scarcityGlobal = scarcityRecord.Global.FormKeyNullable;
            var targetGlobal = preScarcityRecord.Global.FormKeyNullable;

            if (scarcityGlobal == targetGlobal)
                continue;

            if (winningGlobal != scarcityGlobal)
                continue;

            var patch = leveledItemContext.GetOrAddAsOverride(state.PatchMod);
            patch.Global.SetTo(targetGlobal);
            revertedCount++;
            Console.WriteLine($"  Reverted Global on {leveledItem.EditorID} " +
                              $"(was {winningGlobal?.ToString() ?? "null"}, now {targetGlobal?.ToString() ?? "null"})");
        }

        Console.WriteLine($"Reverted {revertedCount} Boss Leveled Item record(s).");
    }

    private const string GoldAnchorEditorId = "Gold001";
    private static void RemoveGoldFromContainers(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Console.WriteLine("Removing gold entries from Container item lists...");

        var goldFormKeys = BuildGoldFormKeySet(state);
        if (goldFormKeys.Count == 0)
        {
            Console.WriteLine($"  Could not locate the {GoldAnchorEditorId} MiscItem in the load order — skipping gold removal.");
            return;
        }

        Console.WriteLine($"  Identified {goldFormKeys.Count} gold-equivalent FormKey(s) (Gold001 plus Leveled Items that resolve to only gold).");
        var containerCount = 0;
        var entryCount = 0;

        foreach (var containerContext in state.LoadOrder.PriorityOrder.Container().WinningContextOverrides())
        {
            var container = containerContext.Record;
            if (container.Items is null || container.Items.Count == 0)
                continue;

            var matchCount = container.Items.Count(e => goldFormKeys.Contains(e.Item.Item.FormKey));
            if (matchCount == 0)
                continue;

            var patch = containerContext.GetOrAddAsOverride(state.PatchMod);
            var removed = patch.Items?.RemoveAll(e => goldFormKeys.Contains(e.Item.Item.FormKey)) ?? 0;

            if (removed == 0)
                continue;

            containerCount++;
            entryCount += removed;
            Console.WriteLine($"  Removed {removed} gold entry/entries from {container.EditorID ?? container.FormKey.ToString()}");
        }

        Console.WriteLine($"Modified {containerCount} Container(s), removed {entryCount} gold entry/entries total.");
    }

    private static HashSet<FormKey> BuildGoldFormKeySet(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var goldFormKeys = new HashSet<FormKey>();

        foreach (var misc in state.LoadOrder.PriorityOrder.MiscItem().WinningOverrides())
        {
            if (string.Equals(misc.EditorID, GoldAnchorEditorId, StringComparison.OrdinalIgnoreCase))
                goldFormKeys.Add(misc.FormKey);
        }

        if (goldFormKeys.Count == 0)
            return goldFormKeys;

        var leveledItems = state.LoadOrder.PriorityOrder.LeveledItem().WinningOverrides().ToList();

        bool changed;
        do
        {
            changed = false;
            foreach (var lvli in leveledItems)
            {
                if (goldFormKeys.Contains(lvli.FormKey))
                    continue;

                if (lvli.Entries is null || lvli.Entries.Count == 0)
                    continue;

                var allGold = true;
                foreach (var entry in lvli.Entries)
                {
                    var refKey = entry.Data?.Reference.FormKey;
                    if (refKey is null || !goldFormKeys.Contains(refKey.Value))
                    {
                        allGold = false;
                        break;
                    }
                }

                if (allGold)
                {
                    goldFormKeys.Add(lvli.FormKey);
                    changed = true;
                }
            }
        } while (changed);

        return goldFormKeys;
    }

    private const string LockRelatedLootPluginName = "LockRelatedLoot.esp";
    private static void ApplyLockRelatedLootCompatibility(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var lrlKey = state.LoadOrder.Keys.FirstOrDefault(
            k => k.FileName.String.Equals(LockRelatedLootPluginName, StringComparison.OrdinalIgnoreCase));

        if (lrlKey.IsNull)
        {
            Console.WriteLine($"{LockRelatedLootPluginName} not present in load order — skipping LRL compatibility step.");
            return;
        }

        Console.WriteLine($"Applying {LockRelatedLootPluginName} compatibility...");

        var lrlMod = state.LoadOrder[lrlKey].Mod;
        if (lrlMod is null)
        {
            Console.WriteLine($"  Could not read {LockRelatedLootPluginName} — skipping.");
            return;
        }

        var updatedCount = 0;
        var scriptsApplied = 0;

        foreach (var lrlContainer in lrlMod.Containers)
        {
            var lrlScripts = lrlContainer.VirtualMachineAdapter?.Scripts;
            if (lrlScripts is null || lrlScripts.Count == 0)
                continue;

            if (!state.LinkCache.TryResolveContext<IContainer, IContainerGetter>(lrlContainer.FormKey, out var winningCtx))
                continue;

            if (winningCtx.ModKey == lrlKey)
                continue;

            var winningRecord = winningCtx.Record;
            var existingScriptNames = new HashSet<string>(
                winningRecord.VirtualMachineAdapter?.Scripts.Select(s => s.Name) ?? Enumerable.Empty<string>(),
                StringComparer.OrdinalIgnoreCase);

            var scriptsToAdd = lrlScripts
                .Where(s => !existingScriptNames.Contains(s.Name))
                .ToList();

            if (scriptsToAdd.Count == 0)
                continue;

            var patch = winningCtx.GetOrAddAsOverride(state.PatchMod);
            patch.VirtualMachineAdapter ??= new VirtualMachineAdapter();
            foreach (var script in scriptsToAdd)
                patch.VirtualMachineAdapter.Scripts.Add(script.DeepCopy());

            updatedCount++;
            scriptsApplied += scriptsToAdd.Count;
            Console.WriteLine($"  Added {scriptsToAdd.Count} script(s) to {winningRecord.EditorID ?? winningRecord.FormKey.ToString()}");
        }

        Console.WriteLine($"Updated {updatedCount} container(s) with {scriptsApplied} script entry/entries from {LockRelatedLootPluginName}.");
    }
}
