using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace ContainerAndLootPatcher;

public class Program
{
    private static Lazy<Settings> _settings = null!;
    private static Settings Settings => _settings.Value;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .Run(args);
    }

    private static IPatcherState<ISkyrimMod, ISkyrimModGetter>? _state;
    internal static IPatcherState<ISkyrimMod, ISkyrimModGetter> State => _state!;

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        _state = state;

        if (Settings.BypassScarcityOnBossLoot)
            BypassScarcityOnBossLoot(state);

        if (Settings.RemoveGoldFromContainers)
            RemoveGoldFromContainers(state);

        if (Settings.LockRelatedLootCompatibility)
            ApplyLockRelatedLootCompatibility(state);
    }

    private static readonly string[] KnownScarcityPluginNames =
    {
        "Scarcity SE - Less Loot Mod.esp",
        "Scarcity - Less Loot Mod.esp"
    };
    
    private static HashSet<FormKey> _scarcityAffectedLists = new();
    private static Dictionary<FormKey, FormKey> _scarcityFreeCloneMap = new();

    private static void BypassScarcityOnBossLoot(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var scarcityKey = state.LoadOrder.Keys.FirstOrDefault(k =>
            KnownScarcityPluginNames.Any(name => k.FileName.String.Equals(name, StringComparison.OrdinalIgnoreCase)));
        if (scarcityKey.IsNull)
        {
            Console.WriteLine($"Warning: Scarcity plugin not found in the load order (checked: {string.Join(", ", KnownScarcityPluginNames)}). Boss-bypass step will be skipped.");
            return;
        }

        Console.WriteLine("Bypassing Scarcity on 'Boss' Container and NPC loot...");

        _scarcityAffectedLists = new HashSet<FormKey>();
        _scarcityFreeCloneMap = new Dictionary<FormKey, FormKey>();

        foreach (var lvli in state.LoadOrder.PriorityOrder.LeveledItem().WinningOverrides())
        {
            var globalKey = lvli.Global.FormKeyNullable;
            if (globalKey is null)
                continue;
            if (globalKey.Value.ModKey == scarcityKey)
                _scarcityAffectedLists.Add(lvli.FormKey);
        }

        if (_scarcityAffectedLists.Count == 0)
        {
            Console.WriteLine("  No Leveled Lists currently use a Scarcity Global — nothing to bypass.");
            return;
        }
        Console.WriteLine($"  Identified {_scarcityAffectedLists.Count} Scarcity-gated Leveled List(s).");

        var containersPatched = 0;
        var npcsPatched = 0;

        foreach (var containerCtx in state.LoadOrder.PriorityOrder.Container().WinningContextOverrides())
        {
            var container = containerCtx.Record;
            if (container.EditorID is null || !container.EditorID.Contains("Boss", StringComparison.OrdinalIgnoreCase))
                continue;
            if (container.Items is null || container.Items.Count == 0)
                continue;
            if (!container.Items.Any(e => _scarcityAffectedLists.Contains(e.Item.Item.FormKey)))
                continue;

            var patch = containerCtx.GetOrAddAsOverride(state.PatchMod);
            var rewired = RewireScarcityRefsInItemList(state, patch.Items);
            if (rewired == 0)
                continue;

            containersPatched++;
            Console.WriteLine($"  Container {container.EditorID}: rewired {rewired} Scarcity-gated entry/entries");
        }

        foreach (var npcCtx in state.LoadOrder.PriorityOrder.Npc().WinningContextOverrides())
        {
            var npc = npcCtx.Record;
            if (npc.EditorID is null || !npc.EditorID.Contains("Boss", StringComparison.OrdinalIgnoreCase))
                continue;
            if (npc.Items is null || npc.Items.Count == 0)
                continue;
            if (!npc.Items.Any(e => _scarcityAffectedLists.Contains(e.Item.Item.FormKey)))
                continue;

            var patch = npcCtx.GetOrAddAsOverride(state.PatchMod);
            var rewired = RewireScarcityRefsInItemList(state, patch.Items);
            if (rewired == 0)
                continue;

            npcsPatched++;
            Console.WriteLine($"  NPC {npc.EditorID}: rewired {rewired} Scarcity-gated entry/entries");
        }

        Console.WriteLine($"Patched {containersPatched} container(s) and {npcsPatched} NPC(s) using {_scarcityFreeCloneMap.Count} Scarcity-free Leveled List clone(s).");
    }

    private static int RewireScarcityRefsInItemList(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, IList<ContainerEntry>? items)
    {
        if (items is null || items.Count == 0)
            return 0;

        var count = 0;
        foreach (var entry in items)
        {
            var refKey = entry.Item.Item.FormKey;
            if (!_scarcityAffectedLists.Contains(refKey))
                continue;

            var cloneKey = GetOrCreateScarcityFreeClone(state, refKey);
            entry.Item.Item.SetTo(cloneKey);
            count++;
        }
        return count;
    }

    private static FormKey GetOrCreateScarcityFreeClone(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, FormKey originalKey)
    {
        if (_scarcityFreeCloneMap.TryGetValue(originalKey, out var existing))
            return existing;

        if (!state.LinkCache.TryResolve<ILeveledItemGetter>(originalKey, out var original))
            return originalKey;

        var clone = new LeveledItem(state.PatchMod.GetNextFormKey(), state.PatchMod.SkyrimRelease)
        {
            EditorID = BuildCloneEditorId(original.EditorID, originalKey)
        };
        state.PatchMod.LeveledItems.Add(clone);
        _scarcityFreeCloneMap[originalKey] = clone.FormKey;

        clone.ChanceNone = original.ChanceNone;
        clone.Flags = original.Flags;
        // Global is deliberately left null — that's the whole point of the clone.

        if (original.Entries is not null && original.Entries.Count > 0)
        {
            clone.Entries = new Noggog.ExtendedList<LeveledItemEntry>();
            foreach (var entryGetter in original.Entries)
            {
                var newEntry = entryGetter.DeepCopy();
                if (newEntry.Data is not null && _scarcityAffectedLists.Contains(newEntry.Data.Reference.FormKey))
                {
                    var subCloneKey = GetOrCreateScarcityFreeClone(state, newEntry.Data.Reference.FormKey);
                    newEntry.Data.Reference.SetTo(subCloneKey);
                }
                clone.Entries.Add(newEntry);
            }
        }

        return clone.FormKey;
    }

    private static string BuildCloneEditorId(string? originalEditorId, FormKey originalKey)
    {
        const string suffix = "_CLP";
        const int maxLength = 99;
        var baseId = string.IsNullOrEmpty(originalEditorId)
            ? $"LVLI_{originalKey.IDString()}"
            : originalEditorId;
        if (baseId.Length + suffix.Length > maxLength)
            baseId = baseId.Substring(0, maxLength - suffix.Length);
        return baseId + suffix;
    }

    private const string GoldAnchorEditorId = "Gold001";
    private static void RemoveGoldFromContainers(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Console.WriteLine("Removing gold entries from Container item lists...");

        var goldFormKeys = BuildGoldFormKeySet(state);
        if (goldFormKeys.Count == 0)
        {
            Console.WriteLine($"  Could not locate the {GoldAnchorEditorId} MiscItem in the load order — skipping gold removal.");
            return;
        }

        Console.WriteLine($"  Identified {goldFormKeys.Count} gold-equivalent FormKey(s) (Gold001 plus Leveled Lists that resolve to only gold).");
        var containerCount = 0;
        var entryCount = 0;

        foreach (var containerContext in state.LoadOrder.PriorityOrder.Container().WinningContextOverrides())
        {
            var container = containerContext.Record;
            if (container.Items is null || container.Items.Count == 0)
                continue;

            var matchCount = container.Items.Count(e => goldFormKeys.Contains(e.Item.Item.FormKey));
            if (matchCount == 0)
                continue;

            var patch = containerContext.GetOrAddAsOverride(state.PatchMod);
            var removed = patch.Items?.RemoveAll(e => goldFormKeys.Contains(e.Item.Item.FormKey)) ?? 0;

            if (removed == 0)
                continue;

            containerCount++;
            entryCount += removed;
            Console.WriteLine($"  Removed {removed} gold entry/entries from {container.EditorID ?? container.FormKey.ToString()}");
        }

        Console.WriteLine($"Modified {containerCount} Container(s), removed {entryCount} gold entry/entries total.");
    }

    private static HashSet<FormKey> BuildGoldFormKeySet(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var goldFormKeys = new HashSet<FormKey>();

        foreach (var misc in state.LoadOrder.PriorityOrder.MiscItem().WinningOverrides())
        {
            if (string.Equals(misc.EditorID, GoldAnchorEditorId, StringComparison.OrdinalIgnoreCase))
                goldFormKeys.Add(misc.FormKey);
        }

        if (goldFormKeys.Count == 0)
            return goldFormKeys;

        var leveledItems = state.LoadOrder.PriorityOrder.LeveledItem().WinningOverrides().ToList();

        bool changed;
        do
        {
            changed = false;
            foreach (var lvli in leveledItems)
            {
                if (goldFormKeys.Contains(lvli.FormKey))
                    continue;

                if (lvli.Entries is null || lvli.Entries.Count == 0)
                    continue;

                var allGold = true;
                foreach (var entry in lvli.Entries)
                {
                    var refKey = entry.Data?.Reference.FormKey;
                    if (refKey is null || !goldFormKeys.Contains(refKey.Value))
                    {
                        allGold = false;
                        break;
                    }
                }

                if (allGold)
                {
                    goldFormKeys.Add(lvli.FormKey);
                    changed = true;
                }
            }
        } while (changed);

        return goldFormKeys;
    }

    private const string LockRelatedLootPluginName = "LockRelatedLoot.esp";
    private static void ApplyLockRelatedLootCompatibility(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var lrlKey = state.LoadOrder.Keys.FirstOrDefault(
            k => k.FileName.String.Equals(LockRelatedLootPluginName, StringComparison.OrdinalIgnoreCase));

        if (lrlKey.IsNull)
        {
            Console.WriteLine($"{LockRelatedLootPluginName} not present in load order — skipping LRL compatibility step.");
            return;
        }

        Console.WriteLine($"Applying {LockRelatedLootPluginName} compatibility...");

        var lrlMod = state.LoadOrder[lrlKey].Mod;
        if (lrlMod is null)
        {
            Console.WriteLine($"  Could not read {LockRelatedLootPluginName} — skipping.");
            return;
        }

        var updatedCount = 0;
        var scriptsApplied = 0;

        foreach (var lrlContainer in lrlMod.Containers)
        {
            var lrlScripts = lrlContainer.VirtualMachineAdapter?.Scripts;
            if (lrlScripts is null || lrlScripts.Count == 0)
                continue;

            if (!state.LinkCache.TryResolveContext<IContainer, IContainerGetter>(lrlContainer.FormKey, out var winningCtx))
                continue;

            if (winningCtx.ModKey == lrlKey)
                continue;

            var winningRecord = winningCtx.Record;
            var existingScriptNames = new HashSet<string>(
                winningRecord.VirtualMachineAdapter?.Scripts.Select(s => s.Name) ?? Enumerable.Empty<string>(),
                StringComparer.OrdinalIgnoreCase);

            var scriptsToAdd = lrlScripts
                .Where(s => !existingScriptNames.Contains(s.Name))
                .ToList();

            if (scriptsToAdd.Count == 0)
                continue;

            var patch = winningCtx.GetOrAddAsOverride(state.PatchMod);
            patch.VirtualMachineAdapter ??= new VirtualMachineAdapter();
            foreach (var script in scriptsToAdd)
                patch.VirtualMachineAdapter.Scripts.Add(script.DeepCopy());

            updatedCount++;
            scriptsApplied += scriptsToAdd.Count;
            Console.WriteLine($"  Added {scriptsToAdd.Count} script(s) to {winningRecord.EditorID ?? winningRecord.FormKey.ToString()}");
        }

        Console.WriteLine($"Updated {updatedCount} container(s) with {scriptsApplied} script entry/entries from {LockRelatedLootPluginName}.");
    }
}
